# pylint: disable=import-outside-toplevel,invalid-name,missing-class-docstring,no-else-return,no-member,too-complex
from products.models._validators import _excel_ext_validator

from django.conf import settings
from django.db import models


class System(models.Model):
    stream = models.ForeignKey("Stream", on_delete=models.CASCADE, related_name="systems")
    STATUS_CHOICES = [
        ("Active", "Active"),
        ("Not Active", "Not Active"),
        ("Issue", "Issue in the system"),
        ("Used", "Used by other team"),
        ("Removed", "Removed/Dismantled"),
    ]
    HEALTH_CHOICES = [
        ("Excellent", "Excellent"),
        ("Good", "Good"),
        ("Warning", "Warning"),
        ("Critical", "Critical"),
    ]
    name = models.CharField(max_length=64, unique=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Active")
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    nc_details = models.TextField(blank=True, null=True)  # Free-text 12NC ordering code details
    health = models.CharField(max_length=20, choices=HEALTH_CHOICES, default="Good")
    utilization_percentage = models.FloatField(default=0.0)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    # get_status_display() and get_health_display() are auto-generated by Django
    # from the ``choices=`` argument on the respective fields.

    def get_current_downtime(self):
        """Get any ongoing downtime for this system"""
        return self.downtime_events.filter(status="ongoing", end_time__isnull=True).first()

    def is_currently_down(self):
        """Check if system is currently experiencing downtime"""
        return self.get_current_downtime() is not None

    def get_downtime_metrics(self, days=30):
        """Get downtime metrics for the specified period"""
        from datetime import timedelta

        from django.utils import timezone

        end_date = timezone.now()
        start_date = end_date - timedelta(days=days)

        metrics, created = SystemDowntimeMetrics.objects.get_or_create(
            system=self, period_start=start_date, period_end=end_date, defaults={"availability_percentage": 100.0}
        )

        if created or metrics.updated_at < timezone.now() - timedelta(hours=1):
            metrics.calculate_metrics()

        return metrics

    def get_availability_percentage(self, days=30):
        """Get system availability percentage for the specified period"""
        metrics = self.get_downtime_metrics(days)
        return metrics.availability_percentage

    def get_total_downtime_hours(self, days=30):
        """Get total downtime hours for the specified period"""
        metrics = self.get_downtime_metrics(days)
        return metrics.total_downtime_hours

    def get_mttr(self, days=30):
        """Get Mean Time To Repair for the specified period"""
        metrics = self.get_downtime_metrics(days)
        return metrics.mean_time_to_repair_hours

    def get_mtbf(self, days=30):
        """Get Mean Time Between Failures for the specified period"""
        metrics = self.get_downtime_metrics(days)
        return metrics.mean_time_between_failures_hours


class SystemMetrics(models.Model):
    system = models.ForeignKey("System", related_name="metrics", on_delete=models.CASCADE)
    usage_hours = models.FloatField(default=0.0)
    total_allocations = models.IntegerField(default=0)
    last_allocation_date = models.DateTimeField(null=True, blank=True)
    average_session_duration = models.DurationField(null=True, blank=True)
    uptime_percentage = models.FloatField(default=100.0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Metrics for {self.system.name}"


class SystemDowntime(models.Model):
    """
    Track system downtime events for comprehensive downtime metrics and analysis
    """

    DOWNTIME_TYPES = [
        ("planned_maintenance", "Planned Maintenance"),
        ("unplanned_maintenance", "Unplanned Maintenance"),
        ("system_failure", "System Failure"),
        ("hardware_failure", "Hardware Failure"),
        ("software_issue", "Software Issue"),
        ("network_issue", "Network Issue"),
        ("power_outage", "Power Outage"),
        ("environmental", "Environmental Issue"),
        ("other", "Other"),
    ]

    IMPACT_LEVELS = [
        ("low", "Low Impact"),
        ("medium", "Medium Impact"),
        ("high", "High Impact"),
        ("critical", "Critical Impact"),
    ]

    STATUS_CHOICES = [
        ("ongoing", "Ongoing"),
        ("resolved", "Resolved"),
        ("investigating", "Under Investigation"),
        ("escalated", "Escalated"),
    ]

    system = models.ForeignKey("System", related_name="downtime_events", on_delete=models.CASCADE)
    stream = models.ForeignKey("Stream", on_delete=models.CASCADE, related_name="downtime_events")

    # Downtime event details
    start_time = models.DateTimeField(help_text="When the downtime started")
    end_time = models.DateTimeField(null=True, blank=True, help_text="When the downtime was resolved")
    downtime_type = models.CharField(max_length=30, choices=DOWNTIME_TYPES, default="other")
    impact_level = models.CharField(max_length=10, choices=IMPACT_LEVELS, default="medium")
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default="ongoing")

    # Description and details
    title = models.CharField(max_length=255, help_text="Brief title describing the downtime")
    description = models.TextField(help_text="Detailed description of the downtime incident")
    root_cause = models.TextField(blank=True, null=True, help_text="Root cause analysis")
    resolution_steps = models.TextField(blank=True, null=True, help_text="Steps taken to resolve the issue")

    # People involved
    reported_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="reported_downtimes"
    )
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="assigned_downtimes"
    )
    resolved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="resolved_downtimes"
    )

    # Tracking and notification
    users_affected = models.ManyToManyField(  # type: ignore[var-annotated]
        settings.AUTH_USER_MODEL, blank=True, related_name="affected_by_downtimes"
    )
    external_ticket_id = models.CharField(
        max_length=100, blank=True, null=True, help_text="External ticket system reference"
    )

    # Metadata
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-start_time"]
        verbose_name = "System Downtime"
        verbose_name_plural = "System Downtimes"

    def __str__(self):
        return f"{self.system.name} - {self.title} ({self.start_time})"

    @property
    def duration(self):
        """Calculate the duration of the downtime"""
        if self.end_time:
            return self.end_time - self.start_time
        else:
            from django.utils import timezone

            return timezone.now() - self.start_time

    @property
    def duration_hours(self):
        """Get duration in hours as float"""
        return self.duration.total_seconds() / 3600

    @property
    def is_ongoing(self):
        """Check if downtime is still ongoing"""
        return self.status == "ongoing" or self.end_time is None

    def get_mttr(self):
        """Mean Time To Repair for this incident"""
        if self.end_time:
            return self.duration
        return None

    def resolve(self, resolved_by_user=None, resolution_notes=None):
        """Mark downtime as resolved"""
        from django.utils import timezone

        self.end_time = timezone.now()
        self.status = "resolved"
        if resolved_by_user:
            self.resolved_by = resolved_by_user
        if resolution_notes:
            self.resolution_steps = resolution_notes
        self.save()


class SystemDowntimeMetrics(models.Model):
    """
    Aggregated downtime metrics for systems over specific time periods
    """

    system = models.ForeignKey("System", related_name="downtime_metrics", on_delete=models.CASCADE)
    period_start = models.DateTimeField()
    period_end = models.DateTimeField()

    # Calculated metrics
    total_downtime_hours = models.FloatField(default=0.0)
    total_incidents = models.IntegerField(default=0)
    planned_downtime_hours = models.FloatField(default=0.0)
    unplanned_downtime_hours = models.FloatField(default=0.0)

    # Availability metrics
    availability_percentage = models.FloatField(default=100.0)
    uptime_percentage = models.FloatField(default=100.0)

    # MTTR and MTBF metrics
    mean_time_to_repair_hours = models.FloatField(null=True, blank=True, help_text="Average time to resolve incidents")
    mean_time_between_failures_hours = models.FloatField(
        null=True, blank=True, help_text="Average time between incidents"
    )

    # Most common issues
    most_common_downtime_type = models.CharField(max_length=30, blank=True, null=True)
    most_common_impact_level = models.CharField(max_length=10, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-period_end"]
        unique_together = ("system", "period_start", "period_end")
        verbose_name = "Downtime Metrics"
        verbose_name_plural = "Downtime Metrics"

    def __str__(self):
        return f"{self.system.name} metrics ({self.period_start.date()} - {self.period_end.date()})"

    def calculate_metrics(self):  # noqa: C901
        """Recalculate all metrics for this period"""
        from django.db.models import Count

        downtimes = SystemDowntime.objects.filter(
            system=self.system, start_time__gte=self.period_start, start_time__lte=self.period_end
        )

        self.total_incidents = downtimes.count()

        total_hours = 0
        planned_hours = 0
        unplanned_hours = 0

        for downtime in downtimes:
            hours = downtime.duration_hours
            total_hours += hours

            if "planned" in downtime.downtime_type:
                planned_hours += hours
            else:
                unplanned_hours += hours

        self.total_downtime_hours = total_hours
        self.planned_downtime_hours = planned_hours
        self.unplanned_downtime_hours = unplanned_hours

        # Calculate availability (assuming 24/7 operation)
        period_hours = (self.period_end - self.period_start).total_seconds() / 3600
        if period_hours > 0:
            self.availability_percentage = max(0, (period_hours - total_hours) / period_hours * 100)
            self.uptime_percentage = self.availability_percentage

        resolved_downtimes = downtimes.filter(status="resolved", end_time__isnull=False)
        if resolved_downtimes.exists():
            total_repair_time = 0
            repair_count = 0
            for downtime in resolved_downtimes:
                if downtime.end_time and downtime.start_time:
                    repair_duration = (downtime.end_time - downtime.start_time).total_seconds() / 3600
                    total_repair_time += repair_duration
                    repair_count += 1

            if repair_count > 0:
                self.mean_time_to_repair_hours = total_repair_time / repair_count

        if self.total_incidents > 1:
            self.mean_time_between_failures_hours = period_hours / self.total_incidents

        common_type = downtimes.values("downtime_type").annotate(count=Count("id")).order_by("-count").first()
        if common_type:
            self.most_common_downtime_type = common_type["downtime_type"]

        common_impact = downtimes.values("impact_level").annotate(count=Count("id")).order_by("-count").first()
        if common_impact:
            self.most_common_impact_level = common_impact["impact_level"]

        self.save()


class BusinessUnit(models.Model):
    """
    Business Unit — the top-level organisational grouping.
    Every Stream belongs to exactly one BU.
    After login the user must select / confirm a BU before anything is displayed.
    """

    bu_name = models.CharField(max_length=64, help_text="BU abbreviation, e.g. 'IGT', 'DI'")
    division = models.CharField(max_length=64, help_text="Division abbreviation, e.g. 'MoS', 'CT'")
    slug = models.CharField(
        max_length=130, unique=True, editable=False, help_text="Auto-generated URL slug: <bu_name>-<division>"
    )
    name = models.CharField(
        max_length=200, blank=True, help_text="Full descriptive name, e.g. 'Image Guided Therapy – Modality Solutions'"
    )
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="created_bus"
    )

    class Meta:
        ordering = ["bu_name", "division"]
        unique_together = [("bu_name", "division")]
        verbose_name = "Business Unit"
        verbose_name_plural = "Business Units"

    def save(self, *args, **kwargs):
        from django.utils.text import slugify

        self.slug = slugify(f"{self.bu_name}-{self.division}")
        if not self.name:
            self.name = f"{self.bu_name} – {self.division}"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.bu_name} – {self.division}"

    def get_active_streams(self):
        return self.streams.filter(is_active=True)


class Stream(models.Model):
    business_unit = models.ForeignKey(
        "BusinessUnit",
        on_delete=models.CASCADE,
        related_name="streams",
        null=True,
        blank=True,
        help_text="The Business Unit this stream belongs to",
    )
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

    # Stream-specific settings
    allow_public_registration = models.BooleanField(
        default=True, help_text="Allow users to request access during registration"
    )
    requires_approval = models.BooleanField(default=True, help_text="Require admin approval for access")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_active_users_count(self):
        """Get count of users with access to this stream.
        UserStreamAccess links to CustomUser via 'custom_user'; CustomUser links to Django User via 'user'.
        """
        return self.userstreamaccess_set.filter(custom_user__user__is_active=True).count()


class SystemStatusHistory(models.Model):
    system = models.ForeignKey("System", related_name="status_history", on_delete=models.CASCADE)
    status = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    assignee = models.CharField(max_length=255, blank=True, null=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)
    updated_at = models.DateTimeField(null=True, blank=True)  # Allow setting custom timestamps

    def get_status_display(self):
        # Use System.STATUS_CHOICES for mapping
        choices = dict(System.STATUS_CHOICES)
        return choices.get(self.status, self.status)

    def __str__(self):
        return f"{self.system.name} - {self.status} by {self.updated_by} at {self.updated_at}"


class UserDataVersion(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.CharField(max_length=255, blank=True)
    data_file = models.FileField(upload_to="user_backups/", null=True, blank=True, validators=[_excel_ext_validator])
    version_number = models.PositiveIntegerField(default=1)
    version_str = models.CharField(max_length=20, default="v1.0.0.1")

    def __str__(self):
        return f"Backup {self.id} at {self.created_at}"


class StreamDeletionHistory(models.Model):
    stream_name = models.CharField(max_length=64)
    deleted_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)
    deleted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.stream_name} deleted by {self.deleted_by} at {self.deleted_at}"
