"""
seed_features — Populate / refresh the Feature + FeatureRoleAccess tables.

Usage:
    python manage.py seed_features            # add new features, skip existing
    python manage.py seed_features --reset    # delete all and re-seed

Idempotent: running without --reset only inserts features whose `code` does
not yet exist.  Existing rows are never overwritten.
"""

# pylint: disable=missing-class-docstring,too-many-lines,too-many-locals

from products.models import Feature, FeatureRoleAccess

from django.core.management.base import BaseCommand

# ─────────────────────────────────────────────────────────────────────────────
#  Master Feature Registry  (v2 — granular View / Manage separation)
#  (code, name, module, icon, description, [url_names], {role: default_access})
# ─────────────────────────────────────────────────────────────────────────────

FEATURES = [
    # ══════════════════════════════════════════════════════════════════════════
    #  DASHBOARD & NAVIGATION
    # ══════════════════════════════════════════════════════════════════════════
    (
        "dashboard",
        "Dashboard",
        "dashboard",
        "fas fa-tachometer-alt",
        "Main dashboard with statistics, widgets and overview",
        ["dashboard", "dashboard_stream", "dashboard_api_data", "update_user_activity"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "bu_selection",
        "BU Selection",
        "dashboard",
        "fas fa-building",
        "Select and switch between Business Units",
        ["select_bu", "change_bu"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "feature_hub",
        "Feature Hub",
        "dashboard",
        "fas fa-th-large",
        "Hub page linking to all advanced features",
        ["feature_hub"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "notifications",
        "Notifications",
        "dashboard",
        "fas fa-bell",
        "View and manage notification alerts",
        ["mark_notifications_read", "toggle_notification_read"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "dashboard_widgets",
        "Dashboard Widgets",
        "dashboard",
        "fas fa-puzzle-piece",
        "Customizable dashboard widget layout",
        ["dashboard_widgets_api", "dashboard_save_layout", "dashboard_reset_widgets", "dashboard_widget_data"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "onboarding",
        "Onboarding Tour",
        "dashboard",
        "fas fa-map-signs",
        "First-time guided walkthrough",
        ["onboarding_status_api", "onboarding_complete_api", "onboarding_reset_api"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "showcase_products",
        "BU Showcase Products",
        "dashboard",
        "fas fa-star",
        "Manage the dashboard product gallery showcase",
        ["showcase_products_api", "showcase_product_update", "showcase_product_delete"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  USER MANAGEMENT  (was 1 feature → 4 granular sub-features)
    # ══════════════════════════════════════════════════════════════════════════
    (
        "user_list_view",
        "View User List",
        "user_mgmt",
        "fas fa-users",
        "Browse the list of registered users",
        ["user_list"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "user_approval",
        "Approve / Decline Users",
        "user_mgmt",
        "fas fa-user-check",
        "Approve or decline pending user registrations",
        ["approve_user", "decline_user"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    (
        "user_role_mgmt",
        "Manage Roles & Access",
        "user_mgmt",
        "fas fa-user-shield",
        "Assign/remove roles, grant/revoke stream access, promote/demote users",
        [
            "assign_role",
            "remove_role",
            "grant_stream_access",
            "revoke_stream_access",
            "promote_user",
            "depromote_user",
            "change_user_role",
        ],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    (
        "user_actions",
        "User Actions & Exports",
        "user_mgmt",
        "fas fa-user-cog",
        "Deactivate, reactivate, remove users; download/upload user data",
        [
            "deactivate_user",
            "reactivate_user",
            "remove_user",
            "download_users_excel",
            "download_users_pdf",
            "upload_products_excel",
            "download_inventory_with_os_binaries_excel",
        ],
        {"user": False, "lab_incharge": False, "admin": False, "super_admin": True},
    ),
    (
        "user_profile",
        "User Profile",
        "user_mgmt",
        "fas fa-user",
        "View and edit user profiles",
        ["user_profile", "user_profile_other"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "participants",
        "Participants",
        "user_mgmt",
        "fas fa-user-friends",
        "Add and remove participant records",
        ["add_participant", "remove_participant"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    (
        "user_backups",
        "User Data Backups",
        "user_mgmt",
        "fas fa-database",
        "Restore or delete user data snapshots",
        ["restore_user_backup", "delete_user_backup"],
        {"user": False, "lab_incharge": False, "admin": False, "super_admin": True},
    ),
    (
        "password_change",
        "Password Change",
        "user_mgmt",
        "fas fa-key",
        "Change own account password",
        ["password_change", "password_change_done"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  STREAM & BU ADMINISTRATION
    # ══════════════════════════════════════════════════════════════════════════
    (
        "manage_streams",
        "Manage Streams",
        "stream_admin",
        "fas fa-stream",
        "Create, rename and delete streams",
        ["manage_streams", "delete_stream", "stream_deletion_history"],
        {"user": False, "lab_incharge": False, "admin": False, "super_admin": True},
    ),
    (
        "manage_bus",
        "Manage Business Units",
        "stream_admin",
        "fas fa-sitemap",
        "Create, edit and request deletion of Business Units",
        ["manage_business_units", "bu_deletion_review", "bu_deletion_cancel"],
        {"user": False, "lab_incharge": False, "admin": False, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  INVENTORY & PRODUCTS  (granular View / Create / Edit / Delete splits)
    # ══════════════════════════════════════════════════════════════════════════
    (
        "product_view",
        "View Products",
        "inventory",
        "fas fa-eye",
        "Browse product listings, details and QR labels",
        [
            "product_list_stream",
            "product_detail_stream",
            "product_history_ajax_stream",
            "download_qr_with_details_stream",
        ],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "product_create",
        "Create Products",
        "inventory",
        "fas fa-plus-circle",
        "Add new products to inventory",
        ["product_create_stream"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "product_edit",
        "Edit Products",
        "inventory",
        "fas fa-edit",
        "Modify existing product details",
        ["product_edit_stream"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "product_delete",
        "Delete Products & Bulk Ops",
        "inventory",
        "fas fa-trash-alt",
        "Delete products and perform bulk operations (delete, status, export)",
        [
            "product_delete_stream",
            "product_bulk_delete_stream",
            "product_bulk_status_stream",
            "product_bulk_export_stream",
        ],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    # ── Categories: View vs Manage ──────────────────────────────────────────
    (
        "categories_view",
        "View Categories",
        "inventory",
        "fas fa-tags",
        "Browse category listings and export CSV",
        ["category_list_stream", "category_export_csv_stream"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "categories_manage",
        "Manage Categories",
        "inventory",
        "fas fa-tag",
        "Create, edit and delete product categories",
        ["category_create_stream", "category_edit_stream", "category_delete_stream", "category_bulk_delete_stream"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ── Locations: View vs Manage ───────────────────────────────────────────
    (
        "locations_view",
        "View Locations",
        "inventory",
        "fas fa-map-marker-alt",
        "Browse physical location listings",
        ["location_list_stream"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "locations_manage",
        "Manage Locations",
        "inventory",
        "fas fa-map-pin",
        "Create, edit and delete physical locations",
        ["location_create_stream", "location_edit_stream", "location_delete_stream"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ── Sub-Level Data: View vs Manage ──────────────────────────────────────
    (
        "sublevel_data_view",
        "View Sub-Level Data",
        "inventory",
        "fas fa-layer-group",
        "Browse sub-level inventory data records",
        ["sub_level_list_stream"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "sublevel_data_manage",
        "Manage Sub-Level Data",
        "inventory",
        "fas fa-database",
        "Delete, bulk-update and export sub-level data",
        ["delete_sub_level", "bulk_delete_sublevels", "bulk_update_sublevels", "export_sublevels"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ── Sub-Level Tools: View vs Manage ─────────────────────────────────────
    (
        "sublevel_tools_view",
        "View Sub-Level Tools",
        "inventory",
        "fas fa-tools",
        "Browse sub-level equipment / tool records",
        ["sub_level_tool_list_stream"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "sublevel_tools_manage",
        "Manage Sub-Level Tools",
        "inventory",
        "fas fa-wrench",
        "Delete, bulk-update and export sub-level tools",
        ["delete_sub_level_tool", "bulk_delete_subleveltools", "bulk_update_subleveltools", "export_subleveltools"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "build_os_info",
        "Build & OS Info",
        "inventory",
        "fas fa-desktop",
        "Build / OS information, Excel previews and merge tools",
        [
            "build_os_info",
            "product_entries_api",
            "add_zenition_product_api",
            "delete_zenition_product_api",
            "os_system_types_api",
            "binaries_system_types_api",
            "system_types_category_mapping_api",
            "test_repo",
            "preview_legacy_excel",
            "preview_zenition_excel",
            "merge_excels",
            "fetch_legacy_excels",
            "preview_legacy_excel_by_filename",
            "save_test_environment",
            "export_data",
            "fetch_zenition_excels",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "delete_excel_files",
        "Delete Excel Files",
        "inventory",
        "fas fa-trash-alt",
        "Delete legacy and zenition excel uploads from the Test Repo page",
        ["delete_legacy_excel"],
        {"user": False, "lab_incharge": False, "admin": False, "super_admin": True},
    ),
    # ── Build Servers: View vs Manage ───────────────────────────────────────
    (
        "build_servers_view",
        "View Build Servers",
        "inventory",
        "fas fa-hdd",
        "Browse build server dashboard, list and export",
        [
            "build_servers_dashboard",
            "build_servers_dashboard_underscore",
            "build_servers_list",
            "build_server_detail",
            "build_servers_api",
            "build_servers_export",
        ],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "build_servers_manage",
        "Manage Build Servers",
        "inventory",
        "fas fa-server",
        "Create, edit and delete build servers",
        ["build_server_create", "build_server_edit", "build_server_delete"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ── Floors: View vs Manage ──────────────────────────────────────────────
    (
        "floors_view",
        "View Floors",
        "inventory",
        "fas fa-building",
        "Browse floor plan listings",
        ["floor_list"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "floors_manage",
        "Manage Floors",
        "inventory",
        "fas fa-drafting-compass",
        "Create, edit and delete floor plans",
        ["floor_create", "floor_edit", "floor_delete"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ── Operating Systems: View vs Manage ───────────────────────────────────
    (
        "os_view",
        "View Operating Systems",
        "inventory",
        "fab fa-windows",
        "Browse operating system records",
        ["operating_system_list"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "os_manage",
        "Manage Operating Systems",
        "inventory",
        "fas fa-cogs",
        "Create, edit and delete OS records",
        ["operating_system_create", "operating_system_edit", "operating_system_delete"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ── Asset Lifecycle: View vs Manage ─────────────────────────────────────
    (
        "asset_lifecycle_view",
        "View Asset Lifecycle",
        "inventory",
        "fas fa-recycle",
        "Browse asset lifecycle records and dashboard",
        ["asset_lifecycle_list", "asset_lifecycle_detail", "asset_lifecycle_dashboard"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "asset_lifecycle_manage",
        "Manage Asset Lifecycle",
        "inventory",
        "fas fa-sync-alt",
        "Create, edit, enroll and transition asset lifecycle records",
        ["asset_lifecycle_bulk_enroll", "asset_lifecycle_create", "asset_lifecycle_edit", "asset_lifecycle_transition"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ── Inventory Alerts: View vs Manage ────────────────────────────────────
    (
        "inventory_alerts_view",
        "View Inventory Alerts",
        "inventory",
        "fas fa-exclamation-circle",
        "Browse active alerts and threshold configurations",
        ["inventory_alerts_list", "inventory_thresholds_list", "inventory_check_all_thresholds"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "inventory_alerts_manage",
        "Manage Inventory Thresholds",
        "inventory",
        "fas fa-sliders-h",
        "Create, edit, delete thresholds; acknowledge and resolve alerts",
        [
            "inventory_threshold_create",
            "inventory_threshold_edit",
            "inventory_threshold_delete",
            "inventory_alert_acknowledge",
            "inventory_alert_resolve",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  SYSTEM ALLOCATION  (View vs Actions + Pool Management)
    # ══════════════════════════════════════════════════════════════════════════
    (
        "system_view",
        "View System Pool",
        "sys_alloc",
        "fas fa-eye",
        "Browse system allocation dashboard, statuses and metrics",
        [
            "system_allocation_stream",
            "system_status_api_stream",
            "system_metrics_api_stream",
            "system_details_api_stream",
            "get_blocked_systems_stream",
            "get_historical_system_status",
            "system_status_history",
            "system_metrics",
            "get_system_metrics",
        ],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "system_actions",
        "Allocate / Release Systems",
        "sys_alloc",
        "fas fa-exchange-alt",
        "Allocate, release, extend and change system options; export logs",
        [
            "allocate_system_stream",
            "release_system_stream",
            "extend_system_stream",
            "opt_change_system_stream",
            "export_systems_log",
            "update_system_metrics",
        ],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "system_pool_manage",
        "System Pool Management",
        "sys_alloc",
        "fas fa-cogs",
        "Add, update, delete systems and reset utilization counters",
        ["add_system_stream", "delete_system_stream", "update_system_stream", "reset_system_utilization_stream"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "nc_details",
        "NC Details",
        "sys_alloc",
        "fas fa-exclamation-triangle",
        "View and manage non-conformance details",
        ["get_nc_details", "save_nc_details", "get_all_nc_details"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "allocation_tree",
        "Allocation Tree",
        "sys_alloc",
        "fas fa-project-diagram",
        "View and manage system grouping tags",
        [
            "allocation_tree_stream",
            "create_system_tag_stream",
            "delete_system_tag_stream",
            "manage_tag_items_stream",
            "get_available_items_stream",
            "get_system_tag_history_stream",
        ],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "downtime",
        "Downtime Tracking",
        "sys_alloc",
        "fas fa-power-off",
        "Track, log and resolve system downtime events",
        [
            "downtime_dashboard",
            "system_downtime_events",
            "system_downtime_events_for_system",
            "system_downtime_event_detail",
            "resolve_downtime",
            "system_downtime_metrics",
            "system_downtime_metrics_for_system",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  RESERVATIONS & BOOKING  (Personal vs Recurring Admin)
    # ══════════════════════════════════════════════════════════════════════════
    (
        "booking_personal",
        "Personal Booking",
        "reservations",
        "fas fa-calendar-check",
        "Quick-book systems, check availability and view personal bookings",
        [
            "reservations_hub",
            "unified_booking_hub",
            "quick_book_system",
            "check_system_availability",
            "my_bookings",
            "api_check_slot_availability",
        ],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "booking_recurring",
        "Recurring Reservations",
        "reservations",
        "fas fa-calendar-alt",
        "Create, edit, delete and manage recurring reservation patterns",
        [
            "recurring_reservations_list",
            "recurring_reservation_create",
            "recurring_reservation_detail",
            "recurring_reservation_edit",
            "recurring_reservation_delete",
            "recurring_reservation_toggle_status",
            "check_recurring_conflicts",
            "reservation_instance_confirm",
            "reservation_instance_cancel",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "utilization",
        "Utilization Dashboard",
        "reservations",
        "fas fa-chart-bar",
        "View system utilization statistics and trends",
        ["utilization_dashboard"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "conflicts",
        "Conflict Resolution",
        "reservations",
        "fas fa-crosshairs",
        "View and resolve booking conflicts between users",
        ["conflicts_list", "conflict_resolve"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "waitlist",
        "Waitlist",
        "reservations",
        "fas fa-clipboard-list",
        "Join, manage and fulfill system waitlists",
        [
            "waitlist_dashboard",
            "waitlist_join",
            "waitlist_entry_detail",
            "waitlist_cancel",
            "waitlist_fulfill",
            "api_get_waitlist_position",
        ],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  CALIBRATION & MAINTENANCE  (View vs Manage)
    # ══════════════════════════════════════════════════════════════════════════
    (
        "calibration_view",
        "View Calibration",
        "calibration",
        "fas fa-search",
        "Browse calibration dashboard, schedules and records",
        [
            "calibration_hub",
            "calibration_dashboard",
            "calibration_schedule_list",
            "calibration_schedule_detail",
            "calibration_records_list",
            "api_calibration_stats",
        ],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "calibration_manage",
        "Manage Calibration",
        "calibration",
        "fas fa-wrench",
        "Create, edit, delete calibration schedules and complete records",
        [
            "calibration_schedule_create",
            "calibration_schedule_edit",
            "calibration_schedule_delete",
            "calibration_record_complete",
            "calibration_record_create",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "maintenance",
        "Maintenance Calendar",
        "calibration",
        "fas fa-calendar-alt",
        "Schedule, track and complete maintenance events",
        [
            "maintenance_calendar",
            "maintenance_calendar_stream",
            "maintenance_calendar_events_api",
            "maintenance_event_create_api",
            "maintenance_event_update_api",
            "maintenance_event_delete_api",
            "maintenance_event_complete_api",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  COMPLIANCE & REGULATORY  (was 1 feature → 5 sub-modules)
    # ══════════════════════════════════════════════════════════════════════════
    (
        "compliance_view",
        "View Compliance Dashboard",
        "compliance",
        "fas fa-shield-alt",
        "Browse compliance hub, dashboard and export reports",
        ["compliance_hub", "compliance_dashboard", "compliance_export_report"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "compliance_documents",
        "Compliance Documents",
        "compliance",
        "fas fa-file-alt",
        "Manage compliance documents, versions and file attachments",
        [
            "compliance_documents_list",
            "compliance_document_create",
            "compliance_document_detail",
            "compliance_document_edit",
            "compliance_document_delete",
            "compliance_document_versions",
            "compliance_document_version_upload",
            "compliance_document_version_restore",
            "compliance_document_version_download",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "compliance_requirements",
        "Regulatory Requirements",
        "compliance",
        "fas fa-clipboard-check",
        "Manage regulatory requirements and standards",
        [
            "regulatory_requirements_list",
            "regulatory_requirement_create",
            "regulatory_requirement_detail",
            "regulatory_requirement_edit",
            "regulatory_requirement_delete",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "compliance_checklists",
        "Regulatory Checklists",
        "compliance",
        "fas fa-tasks",
        "Manage and verify regulatory compliance checklists",
        [
            "regulatory_checklists_list",
            "regulatory_checklist_create",
            "regulatory_checklist_detail",
            "regulatory_checklist_edit",
            "regulatory_checklist_delete",
            "regulatory_checklist_verify",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "compliance_alerts",
        "Compliance Alerts",
        "compliance",
        "fas fa-bell",
        "Create, acknowledge and resolve compliance alert notifications",
        [
            "compliance_alerts_list",
            "compliance_alert_create",
            "compliance_alert_detail",
            "compliance_alert_edit",
            "compliance_alert_delete",
            "compliance_alert_acknowledge",
            "compliance_alert_resolve",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  ANALYTICS & TRACKING
    # ══════════════════════════════════════════════════════════════════════════
    (
        "analytics_dashboard",
        "Analytics Dashboard",
        "analytics",
        "fas fa-chart-line",
        "Charts, metrics and data analytics",
        ["analytics_dashboard"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ── Holistic Dashboard: View vs Manage ──────────────────────────────────
    (
        "holistic_view",
        "View Holistic Dashboard",
        "analytics",
        "fas fa-globe",
        "Browse holistic dashboard, system details, graphs and data",
        [
            "holistic_dashboard",
            "holistic_system_detail",
            "holistic_get_project_assignments",
            "holistic_get_week_data",
            "holistic_all_systems_list",
            "holistic_graph_data",
            "holistic_export_graph_data",
        ],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "holistic_manage",
        "Manage Holistic Systems",
        "analytics",
        "fas fa-edit",
        "Create, edit, delete systems; bulk-update, assign projects, export",
        [
            "holistic_system_create",
            "holistic_system_edit",
            "holistic_system_delete",
            "holistic_weekly_data_update",
            "holistic_export_excel",
            "holistic_export_pdf",
            "holistic_bulk_update",
            "holistic_assign_project_to_week",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "usage_tracking",
        "Usage Tracking",
        "analytics",
        "fas fa-chart-area",
        "Track and analyse system usage patterns",
        ["usage_tracking", "usage_tracking_data"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "personal_trackboard",
        "Personal Trackboard",
        "analytics",
        "fas fa-clipboard",
        "Personal progress and task tracking board",
        ["personal_trackboard"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  COLLABORATION
    # ══════════════════════════════════════════════════════════════════════════
    (
        "notes",
        "Notes",
        "collaboration",
        "fas fa-sticky-note",
        "Create, edit, tag and share personal notes",
        [
            "notes_list",
            "note_detail",
            "note_create",
            "note_edit",
            "note_delete",
            "share_note",
            "shared_notes",
            "shared_by_me",
            "remove_shared_note",
            "note_tags_api",
            "note_tag_create_api",
            "note_tag_delete_api",
            "note_tag_update_api",
        ],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "projects",
        "Projects",
        "collaboration",
        "fas fa-project-diagram",
        "Status board for project tracking and collaboration",
        ["project_status", "delete_project"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "resource_allocation_config",
        "Resource Allocation Config",
        "collaboration",
        "fas fa-users-cog",
        "Configure resource allocation — manage component types, resource persons and allocation years",
        [
            "resource_allocation_config",
            "resource_component_api",
            "resource_person_api",
            "resource_person_assign_api",
            "resource_allocation_api",
            "resource_allocation_export",
            "resource_year_api",
            "resource_weekly_allocation_api",
            "resource_lookup_api",
        ],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    (
        "resource_allocation_lock",
        "Resource Allocation Locking",
        "collaboration",
        "fas fa-lock",
        "Lock and unlock quarterly allocations to prevent edits on finalised periods",
        ["resource_allocation_lock_api"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    (
        "resource_allocation_import",
        "Resource Allocation Import",
        "collaboration",
        "fas fa-file-import",
        "Import resource allocation data from Excel spreadsheets",
        ["resource_allocation_import_api"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    (
        "resource_allocation_notes",
        "Resource Allocation Notes",
        "collaboration",
        "fas fa-sticky-note",
        "Add, edit, and delete cell-level notes and comments on allocation values",
        ["resource_cell_note_api"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "resource_allocation_compare",
        "Resource Allocation Compare",
        "collaboration",
        "fas fa-columns",
        "Compare resource allocations side-by-side across different years",
        ["resource_allocation_compare_api"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "resource_allocation_heatmap",
        "Resource Allocation Heatmap",
        "collaboration",
        "fas fa-th",
        "View demand vs supply heatmap showing FTE utilisation by component and month",
        ["resource_allocation_heatmap_api"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "team_chat",
        "Team Chat",
        "collaboration",
        "fas fa-comments",
        "Real-time team messaging, reactions, file sharing and rooms",
        [
            "team_chat",
            "chat_room_view",
            "chat_api",
            "chat_upload_attachment",
            "chat_react",
            "chat_pin_message",
            "chat_typing_indicator",
            "group_chat_add_member",
            "group_chat_remove_member",
            "chat_room_create",
        ],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "communication",
        "Communication API",
        "collaboration",
        "fas fa-envelope",
        "Internal messaging and attachment sharing API",
        ["communication_api", "upload_communication_attachment", "serve_communication_attachment"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  SUPPORT & HELP  (split Live Support into User vs Admin)
    # ══════════════════════════════════════════════════════════════════════════
    (
        "support_tickets",
        "Support Tickets",
        "support",
        "fas fa-ticket-alt",
        "Create, view and reply to support tickets",
        ["support_ticket_list", "support_ticket_create", "support_ticket_detail"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "live_support_user",
        "Live Support (User)",
        "support",
        "fas fa-headset",
        "Start a real-time support session and send messages",
        ["live_support_start", "live_support_messages", "live_support_close"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "live_support_admin",
        "Live Support Admin Queue",
        "support",
        "fas fa-headset",
        "Admin queue for handling live support requests",
        ["live_support_admin_queue", "live_support_admin_page"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    (
        "faq",
        "FAQ",
        "support",
        "fas fa-question-circle",
        "Frequently Asked Questions",
        ["faq", "faq_stream"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  VENDORS & SUPPLY CHAIN  (was 1 feature → 4 sub-features)
    # ══════════════════════════════════════════════════════════════════════════
    (
        "vendor_view",
        "View Vendors",
        "vendors",
        "fas fa-eye",
        "Browse vendor hub, list, details, analytics and exports",
        ["vendor_hub", "vendor_list", "vendor_detail", "vendor_analytics_api", "vendor_export"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "vendor_manage",
        "Manage Vendors",
        "vendors",
        "fas fa-truck",
        "Create, edit and delete vendor records",
        ["vendor_create", "vendor_edit", "vendor_delete"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    (
        "vendor_contracts",
        "Vendor Contracts & Performance",
        "vendors",
        "fas fa-file-contract",
        "Manage vendor contracts and performance logs",
        ["vendor_contract_create", "vendor_contract_delete", "vendor_performance_log_create"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    (
        "vendor_purchase_orders",
        "Purchase Orders",
        "vendors",
        "fas fa-shopping-cart",
        "Create, track, receive and manage purchase orders",
        ["vendor_po_create", "vendor_po_detail", "vendor_po_update_status", "vendor_po_receive", "vendor_po_delete"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    # ── Waste Management: View vs Manage ────────────────────────────────────
    (
        "waste_view",
        "View Waste Dashboard",
        "vendors",
        "fas fa-chart-pie",
        "Browse waste dashboard, stream details, stats and exports",
        ["waste_dashboard", "waste_stream_detail", "waste_stats_api", "waste_export"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "waste_manage",
        "Manage Waste Records",
        "vendors",
        "fas fa-trash-alt",
        "Create, update, delete waste records, categories and schedules",
        [
            "waste_record_create",
            "waste_record_detail_api",
            "waste_record_update",
            "waste_record_delete",
            "waste_category_api",
            "waste_category_delete",
            "waste_schedule_create",
            "waste_schedule_detail_api",
            "waste_schedule_update",
            "waste_schedule_delete",
            "waste_schedule_assign",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  AI FEATURES
    # ══════════════════════════════════════════════════════════════════════════
    (
        "ai_calibration_reports",
        "AI Calibration Reports",
        "ai",
        "fas fa-file-medical-alt",
        "Auto-generate calibration reports with AI",
        [
            "ai_calibration_report_hub",
            "ai_calibration_report_generate",
            "ai_calibration_report_view",
            "ai_calibration_report_pdf",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "ai_ocr",
        "AI Document OCR",
        "ai",
        "fas fa-file-image",
        "Extract text and data from scanned documents",
        ["ai_ocr_hub", "ai_ocr_process", "ai_ocr_result"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "ai_nl_dashboard",
        "AI Natural Language Query",
        "ai",
        "fas fa-brain",
        "Query data using conversational natural language",
        ["ai_nl_dashboard", "ai_nl_query_api", "ai_nl_feedback_api"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "ai_forecast",
        "AI Inventory Forecast",
        "ai",
        "fas fa-chart-line",
        "Predictive inventory forecasting based on historical data",
        ["ai_inventory_forecast", "ai_inventory_forecast_generate", "ai_inventory_forecast_view"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "ai_scheduler",
        "AI Smart Scheduler",
        "ai",
        "fas fa-magic",
        "Intelligent reservation scheduling recommendations",
        ["ai_smart_scheduler", "ai_smart_scheduler_recommend"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "ai_usage_analytics",
        "AI Usage Analytics",
        "ai",
        "fas fa-chart-pie",
        "AI-powered usage pattern analysis and insights",
        ["ai_usage_analytics", "ai_usage_analytics_generate", "ai_usage_analytics_view"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "ai_anomaly_detection",
        "AI Anomaly Detection",
        "ai",
        "fas fa-search",
        "Detect duplicates and anomalies in inventory data",
        ["ai_anomaly_detection", "ai_anomaly_detection_scan", "ai_anomaly_detection_view"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "ai_model_management",
        "AI Model Management",
        "ai",
        "fas fa-cog",
        "Train, evaluate and manage AI/ML models",
        ["ai_model_management", "ai_train_model_api"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  APPROVAL WORKFLOWS  (dashboard, requests, templates, triggers, settings)
    # ══════════════════════════════════════════════════════════════════════════
    (
        "approval_dashboard_view",
        "View Approval Dashboard",
        "approvals",
        "fas fa-check-double",
        "Access the approval dashboard to view pending, submitted and all requests",
        ["approval_dashboard", "approval_my_pending", "approval_analytics_api"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "approval_request_create",
        "Create Approval Requests",
        "approvals",
        "fas fa-file-signature",
        "Submit new manual approval requests",
        ["approval_request_create"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "approval_request_action",
        "Approve / Reject Requests",
        "approvals",
        "fas fa-gavel",
        "Take action (approve, reject, delegate) on pending approval steps",
        ["approval_request_detail", "approval_request_action", "approval_request_comment"],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "approval_templates_manage",
        "Manage Templates",
        "approvals",
        "fas fa-layer-group",
        "Create, edit and delete approval workflow templates and their steps",
        ["approval_templates_api", "approval_template_detail_api"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    (
        "approval_triggers_manage",
        "Manage Trigger Rules",
        "approvals",
        "fas fa-bolt",
        "Create, edit, enable/disable and delete auto-trigger rules",
        ["approval_triggers_api", "approval_trigger_detail_api"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    (
        "approval_settings",
        "Approval Settings",
        "approvals",
        "fas fa-cog",
        "Manage entity types, event types and approval workflow configuration",
        ["approval_entity_types_api", "approval_event_types_api"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  GLOBAL SEARCH
    # ══════════════════════════════════════════════════════════════════════════
    (
        "global_search",
        "Global Search",
        "search",
        "fas fa-search",
        "Full-text search across all entities (products, systems, vendors, projects, etc.)",
        ["global_search", "global_search_api", "search_suggestions_api", "search_log_click_api"],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "search_reindex",
        "Search Re-Index",
        "search",
        "fas fa-sync-alt",
        "Trigger a full re-index of the search database (admin operation)",
        ["search_reindex_api"],
        {"user": False, "lab_incharge": False, "admin": False, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  ADMINISTRATION & AUDIT  (split View vs Admin actions)
    # ══════════════════════════════════════════════════════════════════════════
    (
        "audit_log_view",
        "View Audit Log",
        "admin",
        "fas fa-history",
        "Browse and export the activity audit trail",
        ["audit_log_list", "audit_log_export", "audit_log_api_data"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    (
        "audit_log_admin",
        "Audit Log Administration",
        "admin",
        "fas fa-trash",
        "Clear audit logs and configure audit settings",
        ["audit_log_clear", "audit_log_settings"],
        {"user": False, "lab_incharge": False, "admin": False, "super_admin": True},
    ),
    (
        "site_settings",
        "Site Settings",
        "admin",
        "fas fa-sliders-h",
        "System-wide configuration and DevTools protection",
        ["get_site_settings", "toggle_devtools_protection"],
        {"user": False, "lab_incharge": False, "admin": False, "super_admin": True},
    ),
    # ── TLD Badges: View vs Manage ──────────────────────────────────────────
    (
        "tld_badges_view",
        "View TLD Badges",
        "admin",
        "fas fa-id-badge",
        "Browse TLD badge dashboard, history and audit log",
        [
            "tld_badge_dashboard",
            "tld_badge_export",
            "tld_badge_check_duplicate",
            "tld_badge_history",
            "tld_badge_audit_log",
            "tld_badge_print",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "tld_badges_manage",
        "Manage TLD Badges",
        "admin",
        "fas fa-id-card",
        "Create, edit, delete and bulk-import TLD badges",
        ["tld_badge_create", "tld_badge_edit", "tld_badge_delete", "tld_badge_bulk_import", "tld_badge_bulk_update"],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  OPERATIONS (Robocopy automation)
    # ══════════════════════════════════════════════════════════════════════════
    (
        "robocopy",
        "Robocopy Automation",
        "admin",
        "fas fa-copy",
        "Execute robocopy file synchronisation commands",
        ["execute_robocopy"],
        {"user": False, "lab_incharge": False, "admin": False, "super_admin": True},
    ),
    # ══════════════════════════════════════════════════════════════════════════
    #  SHIFT HANDOVER LOG
    # ══════════════════════════════════════════════════════════════════════════
    (
        "shift_handover_view",
        "View Shift Handovers",
        "operations",
        "fas fa-exchange-alt",
        "Browse shift handover hub, stream details, and stats",
        [
            "shift_handover_hub",
            "shift_handover_stream",
            "shift_handover_detail_api",
            "shift_handover_stats_api",
            "shift_type_api",
        ],
        {"user": True, "lab_incharge": True, "admin": True, "super_admin": True},
    ),
    (
        "shift_handover_manage",
        "Manage Shift Handovers",
        "operations",
        "fas fa-exchange-alt",
        "Create, edit, delete, submit and acknowledge shift handover logs",
        [
            "shift_handover_create",
            "shift_handover_update",
            "shift_handover_delete",
            "shift_handover_submit",
            "shift_handover_acknowledge",
            "shift_handover_comment",
            "shift_type_delete",
        ],
        {"user": False, "lab_incharge": True, "admin": True, "super_admin": True},
    ),

    # ── PUBLIC REQUESTS (demo + vulnerability) ─────────────────────────
    (
        "public_requests",
        "Public Requests",
        "admin",
        "fas fa-inbox",
        "View and manage demo requests and vulnerability reports from the public home page",
        [
            "public_requests_list",
            "submit_demo_request",
            "submit_vulnerability_report",
            "demo_request_update_status",
            "vulnerability_report_update_status",
        ],
        {"user": False, "lab_incharge": False, "admin": True, "super_admin": True},
    ),
]


class Command(BaseCommand):
    help = "Seed or refresh the Feature registry and default role access."

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset", action="store_true", help="Delete all existing features and re-seed from scratch."
        )

    def handle(self, *args, **options):
        if options["reset"]:
            deleted, _ = Feature.objects.all().delete()
            self.stdout.write(self.style.WARNING(f"Deleted {deleted} rows (Feature + cascade)."))

        created_count = 0
        skipped_count = 0
        roles = ["user", "lab_incharge", "admin", "super_admin", "app_admin"]

        for idx, (code, name, module, icon, desc, url_names, defaults) in enumerate(FEATURES):
            feature, created = Feature.objects.get_or_create(
                code=code,
                defaults={
                    "name": name,
                    "module": module,
                    "icon": icon,
                    "description": desc,
                    "url_names": url_names,
                    "sort_order": idx * 10,
                },
            )

            if created:
                created_count += 1
                # Create role-access rows
                for role in roles:
                    has_access = defaults.get(role, role == "app_admin")
                    FeatureRoleAccess.objects.create(
                        feature=feature,
                        role=role,
                        has_access=has_access,
                    )
                self.stdout.write(f"  + {code}")
            else:
                skipped_count += 1
                # Ensure all roles have an access row (in case new roles were added)
                for role in roles:
                    FeatureRoleAccess.objects.get_or_create(
                        feature=feature,
                        role=role,
                        defaults={"has_access": defaults.get(role, role == "app_admin")},
                    )

        self.stdout.write(self.style.SUCCESS(f"Done — {created_count} created, {skipped_count} existing (skipped)."))
