from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static
from .views import system_allocation, stream_deletion_history, product_entries_api, delete_zenition_product_api, execute_robocopy, CustomPasswordChangeDoneView, custom_password_change, sub_level_list, delete_sub_level, test_repo_view, preview_legacy_excel, preview_zenition_excel, merge_excels, fetch_zenition_excels, os_system_types_api, binaries_system_types_api, system_types_category_mapping_api
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('users/', views.user_list, name='user_list'),
    path('users/change-role/<int:user_id>/', views.change_user_role, name='change_user_role'),
    path('users/promote/<int:user_id>/', views.promote_user, name='promote_user'),
    path('users/remove/<int:user_id>/', views.remove_user, name='remove_user'),
    path('users/depromote/<int:user_id>/', views.depromote_user, name='depromote_user'),    
    path('users/approve/<int:user_id>/', views.approve_user, name='approve_user'),
    path('users/decline/<int:user_id>/', views.decline_user, name='decline_user'),
    # New role and stream management URLs
    path('users/<int:user_id>/assign-role/', views.assign_role, name='assign_role'),
    path('users/<int:user_id>/remove-role/', views.remove_role, name='remove_role'),
    path('users/<int:user_id>/grant-stream/', views.grant_stream_access, name='grant_stream_access'),
    path('users/<int:user_id>/revoke-stream/', views.revoke_stream_access, name='revoke_stream_access'),
    path('manage-streams/', views.manage_streams, name='manage_streams'),
    path('users/download/excel/', views.download_users_excel, name='download_users_excel'),
    path('users/download/pdf/', views.download_users_pdf, name='download_users_pdf'),
    path('users/upload/excel/', views.upload_products_excel, name='upload_products_excel'),
    path('users/add-participant/', views.add_participant, name='add_participant'),
    path('users/remove-participant/<int:participant_id>/', views.remove_participant, name='remove_participant'),
    path('users/download/excel-with-os-binaries/', views.download_inventory_with_os_binaries_excel, name='download_inventory_with_os_binaries_excel'),
    path('users/profile/', views.user_profile, name='user_profile'),
    path('users/profile/<int:user_id>/', views.user_profile, name='user_profile_other'),
    path('stream/<str:stream>/dashboard/', views.dashboard, name='dashboard_stream'),
    path('stream/<str:stream>/categories/', views.category_list, name='category_list_stream'),
    path('stream/<str:stream>/categories/add/', views.category_create, name='category_create_stream'),
    path('stream/<str:stream>/categories/<int:pk>/edit/', views.category_edit, name='category_edit_stream'),
    path('stream/<str:stream>/categories/<int:pk>/delete/', views.category_delete, name='category_delete_stream'),
    path('stream/<str:stream>/categories/bulk-delete/', views.category_bulk_delete, name='category_bulk_delete_stream'),
    path('stream/<str:stream>/categories/export-csv/', views.category_export_csv, name='category_export_csv_stream'),
    path('stream/<str:stream>/products/', views.product_list, name='product_list_stream'),
    path('stream/<str:stream>/products/add/', views.product_create, name='product_create_stream'),
    path('stream/<str:stream>/products/<int:pk>/', views.product_detail, name='product_detail_stream'),
    path('stream/<str:stream>/products/<int:pk>/edit/', views.product_edit, name='product_edit_stream'),
    path('stream/<str:stream>/products/<int:pk>/delete/', views.product_delete, name='product_delete_stream'),
    path('stream/<str:stream>/products/<int:pk>/history/', views.product_history_ajax, name='product_history_ajax_stream'),
    path('stream/<str:stream>/products/<int:pk>/download_qr/', views.download_qr_with_details, name='download_qr_with_details_stream'),
    path('stream/<str:stream>/system-allocation/', views.system_allocation, name='system_allocation_stream'),
    path('stream/<str:stream>/system-allocation/allocate/', views.allocate_system, name='allocate_system_stream'),
    path('stream/<str:stream>/system-allocation/blocked/', views.get_blocked_systems, name='get_blocked_systems_stream'),
    path('stream/<str:stream>/system-allocation/release/', views.release_system, name='release_system_stream'),    
    path('stream/<str:stream>/system-allocation/extend/', views.extend_system, name='extend_system_stream'),
    path('stream/<str:stream>/system-allocation/opt-change/', views.opt_change_system, name='opt_change_system_stream'),
    path('stream/<str:stream>/system-allocation/add-system/', views.add_system, name='add_system_stream'),
    path('stream/<str:stream>/system-allocation/metrics/', views.get_system_metrics, name='get_system_metrics'),
    path('stream/<str:stream>/system-allocation/delete-system/', views.delete_system, name='delete_system_stream'),
    path('stream/<str:stream>/system-allocation/update-system/', views.update_system, name='update_system_stream'),
    path('stream/<str:stream>/system-allocation/reset-utilization/', views.reset_system_utilization, name='reset_system_utilization_stream'),
    path('stream/<str:stream>/system-allocation/status/', views.system_status_api, name='system_status_api_stream'),
    path('stream/<str:stream>/system-allocation/metrics/', views.system_metrics_api, name='system_metrics_api_stream'),
    path('stream/<str:stream>/system-allocation/details/<int:system_id>/', views.system_details_api, name='system_details_api_stream'),
    path('stream/<str:stream>/system-allocation/nc-details/', views.get_nc_details, name='get_nc_details'),
    path('stream/<str:stream>/system-allocation/nc-details/save/', views.save_nc_details, name='save_nc_details'),
    path('stream/<str:stream>/system-allocation/nc-details/all/', views.get_all_nc_details, name='get_all_nc_details'),
    path('stream/<str:stream>/system-allocation/historical-status/', views.get_historical_system_status, name='get_historical_system_status'),
    
    # Downtime tracking URLs
    path('stream/<str:stream>/downtime/', views.downtime_dashboard, name='downtime_dashboard'),
    path('stream/<str:stream>/downtime/events/', views.system_downtime_events, name='system_downtime_events'),
    path('stream/<str:stream>/downtime/events/<int:system_id>/', views.system_downtime_events, name='system_downtime_events_for_system'),
    path('stream/<str:stream>/downtime/event/<int:downtime_id>/', views.system_downtime_event_detail, name='system_downtime_event_detail'),
    path('stream/<str:stream>/downtime/resolve/<int:downtime_id>/', views.resolve_downtime, name='resolve_downtime'),
    path('stream/<str:stream>/downtime/metrics/', views.system_downtime_metrics, name='system_downtime_metrics'),
    path('stream/<str:stream>/downtime/metrics/<int:system_id>/', views.system_downtime_metrics, name='system_downtime_metrics_for_system'),
    path('stream/<str:stream>/location/', views.location_list, name='location_list_stream'),
    path('stream/<str:stream>/location/add/', views.location_create, name='location_create_stream'),
    path('stream/<str:stream>/location/<int:pk>/edit/', views.location_edit, name='location_edit_stream'),
    path('stream/<str:stream>/location/<int:pk>/delete/', views.location_delete, name='location_delete_stream'),
    # Allocation Tree URLs
    path('stream/<str:stream>/allocation-tree/', views.allocation_tree, name='allocation_tree_stream'),
    path('stream/<str:stream>/allocation-tree/create-tag/', views.create_system_tag, name='create_system_tag_stream'),
    path('stream/<str:stream>/allocation-tree/delete-tag/<int:tag_id>/', views.delete_system_tag, name='delete_system_tag_stream'),
    path('stream/<str:stream>/allocation-tree/manage-items/<int:tag_id>/', views.manage_tag_items, name='manage_tag_items_stream'),
    path('stream/<str:stream>/allocation-tree/get-items/', views.get_available_items, name='get_available_items_stream'),
    path('stream/<str:stream>/allocation-tree/history/<int:system_id>/', views.get_system_tag_history, name='get_system_tag_history_stream'),
    path('stream/delete/', views.delete_stream, name='delete_stream'),
    path('stream/<str:stream>/system/<int:system_id>/status-history/', views.system_status_history, name='system_status_history'),
    path('users/restore-backup/<int:backup_id>/', views.restore_user_backup, name='restore_user_backup'),
    path('users/delete-backup/<int:backup_id>/', views.delete_user_backup, name='delete_user_backup'),
    path('analytics_dashboard/', views.analytics_dashboard, name='analytics_dashboard'),
    path('stream-deletion-history/', stream_deletion_history, name='stream_deletion_history'),
    path('build_os_info/', views.build_os_info, name='build_os_info'),
    path('api/product-entries/', product_entries_api, name='product_entries_api'),
    path('api/add-zenition-product/', views.add_zenition_product_api, name='add_zenition_product_api'),
    path('api/delete-zenition-product/', delete_zenition_product_api, name='delete_zenition_product_api'),
    path('api/os-system-types/', os_system_types_api, name='os_system_types_api'),
    path('api/binaries-system-types/', binaries_system_types_api, name='binaries_system_types_api'),
    path('api/system-types-category-mapping/', system_types_category_mapping_api, name='system_types_category_mapping_api'),
    path('api/communication/', views.communication_api, name='communication_api'),
    path('api/communication/upload/', views.upload_communication_attachment, name='upload_communication_attachment'),
    path('api/communication/attachment/<int:attachment_id>/', views.serve_communication_attachment, name='serve_communication_attachment'),
    path('api/execute-robocopy/', execute_robocopy, name='execute_robocopy'),
    path('faq/', views.faq, name='faq'),
    path('stream/<str:stream>/faq/', views.faq, name='faq_stream'),
    path('password_change/', custom_password_change, name='password_change'),
    path('password_change/done/', CustomPasswordChangeDoneView.as_view(), name='password_change_done'),    path('stream/<str:stream>/subleveldata/', sub_level_list, name='sub_level_list_stream'),
    path('stream/<str:stream>/subleveldata/delete/<int:sublevel_id>/', delete_sub_level, name='delete_sub_level'),
    path('stream/<str:stream>/sublevels/bulk-delete/', views.bulk_delete_sublevels, name='bulk_delete_sublevels'),
    path('stream/<str:stream>/sublevels/bulk-update/', views.bulk_update_sublevels, name='bulk_update_sublevels'),
    path('stream/<str:stream>/sublevels/export/', views.export_sublevels, name='export_sublevels'),
    path('stream/<str:stream>/subleveltools/', views.sub_level_tool_list, name='sub_level_tool_list_stream'),
    path('stream/<str:stream>/subleveltools/delete/<int:subleveltool_id>/', views.delete_sub_level_tool, name='delete_sub_level_tool'),
    path('stream/<str:stream>/subleveltools/bulk-delete/', views.bulk_delete_subleveltools, name='bulk_delete_subleveltools'),
    path('stream/<str:stream>/subleveltools/bulk-update/', views.bulk_update_subleveltools, name='bulk_update_subleveltools'),
    path('stream/<str:stream>/subleveltools/export/', views.export_subleveltools, name='export_subleveltools'),
    path('notifications/mark_read/', views.mark_notifications_read, name='mark_notifications_read'),
    path('test-repo/', test_repo_view, name='test_repo'),
    path('preview-legacy-excel/<int:upload_id>/', preview_legacy_excel, name='preview_legacy_excel'),
    path('preview-zenition-excel/<int:upload_id>/', preview_zenition_excel, name='preview_zenition_excel'),
    path('merge-excels/', merge_excels, name='merge_excels'),
    path('fetch-legacy-excels/', views.fetch_legacy_excels, name='fetch_legacy_excels'),
    path('preview-legacy-excel-by-filename/<str:filename>/', views.preview_legacy_excel_by_filename, name='preview_legacy_excel_by_filename'),
    path('save-test-environment/', views.save_test_environment, name='save_test_environment'),
    path('export-data/', views.export_data, name='export_data'),
    path('fetch-zenition-excels/', fetch_zenition_excels, name='fetch_zenition_excels'),
    path('personal_trackboard/', views.personal_trackboard, name='personal_trackboard'),
    path('usage-tracking/', views.usage_tracking, name='usage_tracking'),
    path('usage-tracking-data/', views.usage_tracking_data, name='usage_tracking_data'),
    # API endpoints for dashboard
    path('api/dashboard/data/', views.dashboard_api_data, name='dashboard_api_data'),
    path('api/dashboard/activity/', views.update_user_activity, name='update_user_activity'),
    path('system/metrics/<int:system_id>/', views.system_metrics, name='system_metrics'),
    path('system/metrics/update/<int:system_id>/', views.update_system_metrics, name='update_system_metrics'),
    path('stream/<str:stream>/export-systems-log/', views.export_systems_log, name='export_systems_log'),
    path('notes/', views.notes_list, name='notes_list'),
    path('notes/<int:pk>/', views.note_detail, name='note_detail'),
    path('notes/create/', views.note_create, name='note_create'),
    path('notes/<int:pk>/edit/', views.note_edit, name='note_edit'),
    path('notes/<int:pk>/delete/', views.note_delete, name='note_delete'),
    path('notes/<int:pk>/share/', views.share_note, name='share_note'),
    path('notes/shared/', views.shared_notes, name='shared_notes'),
    path('notes/shared-by-me/', views.shared_by_me, name='shared_by_me'),
    path('shared-notes/<int:pk>/remove/', views.remove_shared_note, name='remove_shared_note'),
    # Project Status URLs
    path('projects/', views.project_status, name='project_status'),
    path('projects/delete/', views.delete_project, name='delete_project'),
    
    # Holistic Dashboard URLs (independent, no stream)
    path('holistic-dashboard/', views.holistic_dashboard, name='holistic_dashboard'),
    path('holistic-dashboard/create/', views.holistic_system_create, name='holistic_system_create'),
    path('holistic-dashboard/<int:pk>/', views.holistic_system_detail, name='holistic_system_detail'),
    path('holistic-dashboard/<int:pk>/edit/', views.holistic_system_edit, name='holistic_system_edit'),
    path('holistic-dashboard/<int:pk>/delete/', views.holistic_system_delete, name='holistic_system_delete'),
    path('holistic-dashboard/weekly-data/update/', views.holistic_weekly_data_update, name='holistic_weekly_data_update'),
    path('holistic-dashboard/export/excel/', views.holistic_export_excel, name='holistic_export_excel'),
    path('holistic-dashboard/export/pdf/', views.holistic_export_pdf, name='holistic_export_pdf'),
    path('holistic-dashboard/bulk-update/', views.holistic_bulk_update, name='holistic_bulk_update'),
    path('holistic-dashboard/assign-project-to-week/', views.holistic_assign_project_to_week, name='holistic_assign_project_to_week'),
    path('holistic-dashboard/get-project-assignments/', views.holistic_get_project_assignments, name='holistic_get_project_assignments'),
    path('holistic-dashboard/get-week-data/', views.holistic_get_week_data, name='holistic_get_week_data'),
    path('holistic-dashboard/all-systems-list/', views.holistic_all_systems_list, name='holistic_all_systems_list'),
    path('holistic-dashboard/graph-data/<int:system_id>/', views.holistic_graph_data, name='holistic_graph_data'),
    path('holistic-dashboard/export-graph-data/<int:system_id>/', views.holistic_export_graph_data, name='holistic_export_graph_data'),
    
    # Build Servers URLs
    path('build-servers/', views.build_servers_dashboard, name='build_servers_dashboard'),
    path('build_servers_dashboard/', views.build_servers_dashboard, name='build_servers_dashboard_underscore'),
    path('stream/<str:stream>/build-servers/', views.build_servers_list, name='build_servers_list'),
    path('stream/<str:stream>/build-servers/create/', views.build_server_create, name='build_server_create'),
    path('stream/<str:stream>/build-servers/<int:server_id>/', views.build_server_detail, name='build_server_detail'),
    path('stream/<str:stream>/build-servers/<int:server_id>/edit/', views.build_server_edit, name='build_server_edit'),
    path('stream/<str:stream>/build-servers/<int:server_id>/delete/', views.build_server_delete, name='build_server_delete'),
    path('stream/<str:stream>/build-servers/api/', views.build_servers_api, name='build_servers_api'),
    path('stream/<str:stream>/build-servers/export/', views.build_servers_export, name='build_servers_export'),
    
    # Floor Management URLs (Stream-specific)
    path('stream/<str:stream>/floors/', views.floor_list, name='floor_list'),
    path('stream/<str:stream>/floors/create/', views.floor_create, name='floor_create'),
    path('stream/<str:stream>/floors/<int:floor_id>/edit/', views.floor_edit, name='floor_edit'),
    path('stream/<str:stream>/floors/<int:floor_id>/delete/', views.floor_delete, name='floor_delete'),
    path('stream/<str:stream>/operating-systems/', views.operating_system_list, name='operating_system_list'),
    path('stream/<str:stream>/operating-systems/create/', views.operating_system_create, name='operating_system_create'),
    path('stream/<str:stream>/operating-systems/<int:os_id>/edit/', views.operating_system_edit, name='operating_system_edit'),
    path('stream/<str:stream>/operating-systems/<int:os_id>/delete/', views.operating_system_delete, name='operating_system_delete'),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
