# Generated by Django 5.2.6 on 2026-01-18 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Floor Name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Floor",
                "verbose_name_plural": "Floors",
                "ordering": ["stream", "name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("address", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("stream", models.CharField(blank=True, max_length=100, null=True)),
                ("in_stock", models.PositiveIntegerField(default=0)),
                ("in_use", models.PositiveIntegerField(default=0)),
                ("scraped", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubLevelTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("stream", models.CharField(blank=True, max_length=100, null=True)),
                ("in_stock", models.PositiveIntegerField(default=0)),
                ("in_use", models.PositiveIntegerField(default=0)),
                ("scraped", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("maintenance", "Maintenance"),
                            ("offline", "Offline"),
                            ("warning", "Warning"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("uptime_percentage", models.FloatField(default=99.9)),
                ("active_users", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="TestEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mvs_binaries", models.CharField(blank=True, max_length=255)),
                ("mvs_os", models.CharField(blank=True, max_length=255)),
                ("stand_binaries", models.CharField(blank=True, max_length=255)),
                ("stand_os", models.CharField(blank=True, max_length=255)),
                ("apps_pc_binaries", models.CharField(blank=True, max_length=255)),
                ("apps_pc_os", models.CharField(blank=True, max_length=255)),
                ("test_environment", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZenitionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BinariesSystemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Binaries System Type"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_binaries_system_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_binaries_system_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Binaries System Type",
                "verbose_name_plural": "Binaries System Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BuildServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Machine Hostname"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("location", models.CharField(max_length=255, verbose_name="Location")),
                ("owner", models.CharField(max_length=255, verbose_name="Owner")),
                (
                    "stream_type",
                    models.CharField(
                        choices=[("PIC", "PIC"), ("HIC", "HIC"), ("Other", "Other")],
                        max_length=10,
                        verbose_name="Stream Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Maintenance", "Under Maintenance"),
                            ("Offline", "Offline"),
                        ],
                        default="Active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Operating System",
                    ),
                ),
                (
                    "cpu_cores",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="CPU Cores"
                    ),
                ),
                (
                    "ram_gb",
                    models.IntegerField(blank=True, null=True, verbose_name="RAM (GB)"),
                ),
                (
                    "storage_gb",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Storage (GB)"
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="MAC Address"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Domain"
                    ),
                ),
                ("ssh_port", models.IntegerField(default=22, verbose_name="SSH Port")),
                (
                    "purpose",
                    models.TextField(
                        blank=True, null=True, verbose_name="Purpose/Description"
                    ),
                ),
                (
                    "project_allocation",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Project Allocation",
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Cost Center",
                    ),
                ),
                (
                    "procurement_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Procurement Date"
                    ),
                ),
                (
                    "warranty_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="Warranty Expiry"
                    ),
                ),
                (
                    "primary_contact",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Primary Contact",
                    ),
                ),
                (
                    "secondary_contact",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Secondary Contact",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "last_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Maintenance Date"
                    ),
                ),
                (
                    "next_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Maintenance Date"
                    ),
                ),
                (
                    "uptime_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=99.9,
                        max_digits=5,
                        verbose_name="Uptime %",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Additional Notes"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Tags (comma-separated)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_build_servers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_build_servers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.floor",
                        verbose_name="Floor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Build Server",
                "verbose_name_plural": "Build Servers",
                "ordering": ["hostname"],
            },
        ),
        migrations.CreateModel(
            name="BuildServerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("status_changed", "Status Changed"),
                            ("maintenance", "Maintenance Performed"),
                            ("relocated", "Relocated"),
                            ("specs_updated", "Specifications Updated"),
                            ("ownership_changed", "Ownership Changed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Details about what changed"
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, help_text="Previous values (JSON)", null=True
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, help_text="New values (JSON)", null=True
                    ),
                ),
                (
                    "build_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="products.buildserver",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="build_server_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Build Server History",
                "verbose_name_plural": "Build Server Histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BuildServerMaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine Maintenance"),
                            ("emergency", "Emergency Repair"),
                            ("upgrade", "Hardware Upgrade"),
                            ("software", "Software Update"),
                            ("security", "Security Patch"),
                            ("cleaning", "Physical Cleaning"),
                            ("relocation", "Physical Relocation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(verbose_name="Scheduled Date/Time"),
                ),
                (
                    "actual_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Actual Date/Time"
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Duration (hours)",
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(max_length=255, verbose_name="Performed By"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Maintenance Description"),
                ),
                (
                    "issues_found",
                    models.TextField(
                        blank=True, null=True, verbose_name="Issues Found"
                    ),
                ),
                (
                    "actions_taken",
                    models.TextField(
                        blank=True, null=True, verbose_name="Actions Taken"
                    ),
                ),
                (
                    "parts_replaced",
                    models.TextField(
                        blank=True, null=True, verbose_name="Parts Replaced"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, verbose_name="Completed Successfully"
                    ),
                ),
                (
                    "requires_followup",
                    models.BooleanField(
                        default=False, verbose_name="Requires Follow-up"
                    ),
                ),
                (
                    "next_maintenance_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Maintenance Due"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Vendor/Contractor",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "build_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="products.buildserver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Log",
                "verbose_name_plural": "Maintenance Logs",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("serial_number", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page", models.CharField(default="build_os_info", max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunicationAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="communication_attachments/%Y/%m/"),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "communication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="products.communication",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HolisticSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sr_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Serial Number"
                    ),
                ),
                (
                    "system_availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("allocated", "Allocated"),
                            ("maintenance", "Maintenance"),
                            ("reserved", "Reserved"),
                            ("offline", "Offline"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="System Availability",
                    ),
                ),
                (
                    "allocation_to_sl_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Allocation to Sl No",
                    ),
                ),
                (
                    "location_info",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Location Info",
                    ),
                ),
                (
                    "stmi_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="STMi Number",
                    ),
                ),
                (
                    "system_owner",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="System Owner",
                    ),
                ),
                (
                    "ecr_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ECR#"
                    ),
                ),
                (
                    "test_engineer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Test Engineer",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_holistic_systems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_holistic_systems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Holistic System",
                "verbose_name_plural": "Holistic Systems",
                "ordering": ["sr_no"],
            },
        ),
        migrations.CreateModel(
            name="HolisticSystemHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField(blank=True)),
                (
                    "holistic_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="products.holisticsystem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System History",
                "verbose_name_plural": "System Histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LegacyExcelUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stream", models.CharField(max_length=64)),
                ("file", models.FileField(upload_to="legacy_excels/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("preview_data", models.TextField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="note_attachments/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("spreadsheet", "Spreadsheet"),
                            ("pdf", "PDF"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="products.note",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=512)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("allocation", "System Allocation"),
                            ("backup", "Backup Completion"),
                            ("admin", "Admin Action"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OSSystemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="OS System Type"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_os_system_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_os_system_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OS System Type",
                "verbose_name_plural": "OS System Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PersonalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("inprogress", "In Progress"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("serial_number", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Not Active", "Not Active"),
                            ("Scraped", "Scraped"),
                            ("Hand-Overed", "Hand-Overed"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "handover_team_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "handover_external_team",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "handover_owner",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issue_description", models.TextField(blank=True, null=True)),
                ("twelve_nc", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=32)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allow_public_registration",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users to request access during registration",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True, help_text="Require admin approval for access"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "duration",
                    models.CharField(
                        help_text="e.g., '3 months', '6 weeks', etc.", max_length=100
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "initial_release_date",
                    models.DateField(
                        blank=True, help_text="Initial planned release date", null=True
                    ),
                ),
                (
                    "final_release_date",
                    models.DateField(
                        blank=True, help_text="Final/actual release date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("hold", "On Hold"),
                            ("planned", "Planned"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Actual project completion percentage (0-100)",
                    ),
                ),
                (
                    "expected_progress",
                    models.IntegerField(
                        default=0,
                        help_text="Expected progress based on timeline (0-100)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="products.stream",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.stream",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="products.stream",
            ),
        ),
        migrations.AddField(
            model_name="holisticsystem",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holistic_systems",
                to="products.stream",
            ),
        ),
        migrations.AddField(
            model_name="floor",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floors",
                to="products.stream",
                verbose_name="Stream",
            ),
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_streams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="requested_by_users",
                        to="products.stream",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="products.stream",
            ),
        ),
        migrations.AddField(
            model_name="buildserver",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="build_servers",
                to="products.stream",
            ),
        ),
        migrations.CreateModel(
            name="StreamDeletionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stream_name", models.CharField(max_length=64)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubLevelHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=32)),
                ("by", models.CharField(max_length=255)),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField()),
                (
                    "sublevel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="products.sublevel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubLevelToolHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=32)),
                ("by", models.CharField(max_length=255)),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField()),
                (
                    "subleveltool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="products.subleveltool",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Not Active", "Not Active"),
                            ("Issue", "Issue in the system"),
                            ("Used", "Used by other team"),
                            ("Removed", "Removed/Dismantled"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("nc_details", models.TextField(blank=True, null=True)),
                (
                    "health",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Warning", "Warning"),
                            ("Critical", "Critical"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("utilization_percentage", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systems",
                        to="products.stream",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("Z70 Full system", "Z70 Full system"),
                            ("Z50 Table top", "Z50 Table top"),
                            ("Z90 Full system", "Z90 Full system"),
                            ("Z70/90 Rack System", "Z70/90 Rack System"),
                            ("Z70/90 Table top", "Z70/90 Table top"),
                            ("Z90 Table top", "Z90 Table top"),
                            ("Z30 Table top", "Z30 Table top"),
                            ("Z10 Table top", "Z10 Table top"),
                        ],
                        max_length=64,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked_for_participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.participant",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_allocations",
                        to="products.stream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemDowntime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="When the downtime started"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the downtime was resolved",
                        null=True,
                    ),
                ),
                (
                    "downtime_type",
                    models.CharField(
                        choices=[
                            ("planned_maintenance", "Planned Maintenance"),
                            ("unplanned_maintenance", "Unplanned Maintenance"),
                            ("system_failure", "System Failure"),
                            ("hardware_failure", "Hardware Failure"),
                            ("software_issue", "Software Issue"),
                            ("network_issue", "Network Issue"),
                            ("power_outage", "Power Outage"),
                            ("environmental", "Environmental Issue"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "impact_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Impact"),
                            ("medium", "Medium Impact"),
                            ("high", "High Impact"),
                            ("critical", "Critical Impact"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("resolved", "Resolved"),
                            ("investigating", "Under Investigation"),
                            ("escalated", "Escalated"),
                        ],
                        default="ongoing",
                        max_length=15,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title describing the downtime", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the downtime incident"
                    ),
                ),
                (
                    "root_cause",
                    models.TextField(
                        blank=True, help_text="Root cause analysis", null=True
                    ),
                ),
                (
                    "resolution_steps",
                    models.TextField(
                        blank=True,
                        help_text="Steps taken to resolve the issue",
                        null=True,
                    ),
                ),
                (
                    "external_ticket_id",
                    models.CharField(
                        blank=True,
                        help_text="External ticket system reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_downtimes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_downtimes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_downtimes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downtime_events",
                        to="products.stream",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downtime_events",
                        to="products.system",
                    ),
                ),
                (
                    "users_affected",
                    models.ManyToManyField(
                        blank=True,
                        related_name="affected_by_downtimes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Downtime",
                "verbose_name_plural": "System Downtimes",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_hours", models.FloatField(default=0.0)),
                ("total_allocations", models.IntegerField(default=0)),
                ("last_allocation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "average_session_duration",
                    models.DurationField(blank=True, null=True),
                ),
                ("uptime_percentage", models.FloatField(default=100.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="products.system",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("assignee", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="products.system",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDataVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "data_file",
                    models.FileField(blank=True, null=True, upload_to="user_backups/"),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("version_str", models.CharField(default="v1.0.0.1", max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="ProductEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("OS", "OS"), ("Binaries", "Binaries")], max_length=20
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                (
                    "subcategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("link", models.URLField(max_length=500)),
                (
                    "binaries_system_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.binariessystemtype",
                        verbose_name="Binaries System Type",
                    ),
                ),
                (
                    "os_system_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.ossystemtype",
                        verbose_name="OS System Type",
                    ),
                ),
                (
                    "zenition_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="products.zenitionproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HolisticWeeklyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.IntegerField(verbose_name="Week Number (e.g., 26 for W26)"),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
                (
                    "allocation_status",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Allocation Status",
                    ),
                ),
                (
                    "utilization_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Utilization %",
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "task_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Task Description"
                    ),
                ),
                (
                    "hours_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=6,
                        verbose_name="Hours Used",
                    ),
                ),
                (
                    "availability_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        max_digits=6,
                        verbose_name="Available Hours",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Weekly Notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "holistic_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_data",
                        to="products.holisticsystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekly_assignments",
                        to="products.project",
                        verbose_name="Project for this week",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Data",
                "verbose_name_plural": "Weekly Data",
                "ordering": ["year", "week_number"],
                "unique_together": {("holistic_system", "week_number", "year")},
            },
        ),
        migrations.CreateModel(
            name="SharedNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message from the sender"
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="products.note",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-shared_at"],
                "unique_together": {("note", "shared_by", "shared_with")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="floor",
            unique_together={("name", "stream")},
        ),
        migrations.CreateModel(
            name="SystemDowntimeMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("total_downtime_hours", models.FloatField(default=0.0)),
                ("total_incidents", models.IntegerField(default=0)),
                ("planned_downtime_hours", models.FloatField(default=0.0)),
                ("unplanned_downtime_hours", models.FloatField(default=0.0)),
                ("availability_percentage", models.FloatField(default=100.0)),
                ("uptime_percentage", models.FloatField(default=100.0)),
                (
                    "mean_time_to_repair_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Average time to resolve incidents",
                        null=True,
                    ),
                ),
                (
                    "mean_time_between_failures_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Average time between incidents",
                        null=True,
                    ),
                ),
                (
                    "most_common_downtime_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "most_common_impact_level",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downtime_metrics",
                        to="products.system",
                    ),
                ),
            ],
            options={
                "verbose_name": "Downtime Metrics",
                "verbose_name_plural": "Downtime Metrics",
                "ordering": ["-period_end"],
                "unique_together": {("system", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="SystemTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_name",
                    models.CharField(
                        help_text="Unique tag identifier for this system",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this system configuration",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="system_tags", to="products.product"
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True, related_name="system_tags", to="products.project"
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_tags",
                        to="products.stream",
                    ),
                ),
                (
                    "sublevel_tools",
                    models.ManyToManyField(
                        blank=True,
                        related_name="system_tags",
                        to="products.subleveltool",
                    ),
                ),
                (
                    "sublevels",
                    models.ManyToManyField(
                        blank=True, related_name="system_tags", to="products.sublevel"
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="products.system",
                    ),
                ),
            ],
            options={
                "ordering": ["system__name", "tag_name"],
                "unique_together": {("system", "tag_name")},
            },
        ),
        migrations.CreateModel(
            name="UsageTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_name", models.CharField(max_length=255)),
                ("page_url", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(blank=True, max_length=64, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("session_duration", models.DurationField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="products_us_user_id_54e929_idx"
                    ),
                    models.Index(
                        fields=["page_name"], name="products_us_page_na_c23084_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="products_us_timesta_2c0b46_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Regular User"),
                            ("lab_incharge", "Lab Incharge"),
                            ("admin", "Admin"),
                            ("super_admin", "Super Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "custom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="products.customuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("custom_user", "role")},
            },
        ),
        migrations.CreateModel(
            name="UserStreamAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "custom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_access",
                        to="products.customuser",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.stream",
                    ),
                ),
            ],
            options={
                "unique_together": {("custom_user", "stream")},
            },
        ),
    ]
