# Generated by Django 5.1.6 on 2026-04-11 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notetag",
            name="color",
            field=models.CharField(
                choices=[
                    ("#3b82f6", "Blue"),
                    ("#059669", "Green"),
                    ("#d97706", "Amber"),
                    ("#dc2626", "Red"),
                    ("#0044CC", "Dark Blue"),
                    ("#0891b2", "Cyan"),
                    ("#0B5FFF", "Royal Blue"),
                    ("#4b5563", "Gray"),
                    ("#b8860b", "Bronze"),
                    ("#65a30d", "Lime"),
                ],
                default="#3b82f6",
                help_text="Hex color code for the tag badge",
                max_length=7,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("current_step", models.PositiveSmallIntegerField(default=1)),
                ("total_steps", models.PositiveSmallIntegerField(default=1)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="products.businessunit",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="products.stream",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="products.approvalrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStepAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_order", models.PositiveSmallIntegerField()),
                ("step_name", models.CharField(max_length=200)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("delegated", "Delegated"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_actions_taken",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_actions",
                        to="products.approvalrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["request", "step_order"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalWorkflowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("purchase_order", "Purchase Order"),
                            ("compliance_document", "Compliance Document"),
                            ("system_decommission", "System Decommission"),
                            ("vendor_onboarding", "Vendor Onboarding"),
                            ("inventory_change", "Inventory Change"),
                            ("asset_disposal", "Asset Disposal"),
                            ("calibration_waiver", "Calibration Waiver"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=40,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "require_all_steps",
                    models.BooleanField(
                        default=True,
                        help_text="If True, all steps must approve. If False, approval at any step finalises.",
                    ),
                ),
                (
                    "auto_approve_timeout_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Auto-approve if no action after this many hours (0 = disabled).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_templates",
                        to="products.businessunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_approval_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="products.approvalworkflowtemplate",
            ),
        ),
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("vendor", "Vendor"),
                            ("compliance_doc", "Compliance Document"),
                            ("calibration", "Calibration Record"),
                            ("system", "System"),
                            ("ticket", "System Ticket"),
                            ("chat_message", "Chat Message"),
                            ("note", "Note"),
                            ("project", "Project"),
                            ("purchase_order", "Purchase Order"),
                            ("build_server", "Build Server"),
                            ("waste_record", "Waste Record"),
                            ("support_ticket", "Support Ticket"),
                            ("approval_request", "Approval Request"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField(db_index=True)),
                ("title", models.CharField(max_length=500)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Concatenated searchable text"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Relative URL to the entity detail page",
                        max_length=500,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome icon class", max_length=60
                    ),
                ),
                (
                    "stream_name",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "business_unit_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=40)),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary metadata for display",
                    ),
                ),
                ("indexed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-indexed_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "business_unit_id"],
                        name="products_se_entity__c1c6b5_idx",
                    ),
                    models.Index(fields=["title"], name="products_se_title_9fe14c_idx"),
                ],
                "unique_together": {("entity_type", "entity_id")},
            },
        ),
        migrations.CreateModel(
            name="SearchQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.CharField(max_length=500)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("entity_type_filter", models.CharField(blank=True, max_length=30)),
                ("clicked_result_type", models.CharField(blank=True, max_length=30)),
                (
                    "clicked_result_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStepTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="1-based step order — lower runs first."
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "approver_type",
                    models.CharField(
                        choices=[
                            ("role", "Any user with role"),
                            ("specific_user", "Specific user"),
                            ("manager", "Stream / BU manager"),
                        ],
                        default="role",
                        max_length=20,
                    ),
                ),
                (
                    "approver_role",
                    models.CharField(
                        blank=True,
                        help_text="Required role (e.g. admin, super_admin) when approver_type = role.",
                        max_length=20,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "approver_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user when approver_type = specific_user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_step_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="products.approvalworkflowtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "order"],
                "unique_together": {("template", "order")},
            },
        ),
    ]
