# Generated by Django 5.1.6 on 2026-04-11 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_alter_notetag_color_approvalrequest_approvalcomment_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalAutoTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable rule name shown in audit trail",
                        max_length=200,
                    ),
                ),
                (
                    "event_action",
                    models.CharField(
                        choices=[
                            ("product_scrapped", "Product → Scrapped"),
                            ("product_handovered", "Product → Hand-Overed"),
                            ("product_deleted", "Product → Deleted"),
                            ("product_bulk_delete", "Product → Bulk Delete"),
                            ("product_bulk_status", "Product → Bulk Status Change"),
                            (
                                "server_decommission",
                                "Build Server → Decommissioned (Inactive/Offline)",
                            ),
                            ("server_deleted", "Build Server → Deleted"),
                            ("compliance_doc_approved", "Compliance Doc → Approved"),
                            (
                                "compliance_doc_archived",
                                "Compliance Doc → Archived / Superseded",
                            ),
                            ("compliance_doc_deleted", "Compliance Doc → Deleted"),
                            ("vendor_onboarded", "Vendor → Onboarded (New)"),
                            ("vendor_blacklisted", "Vendor → Blacklisted"),
                            ("vendor_deleted", "Vendor → Deleted"),
                            ("calibration_waiver", "Calibration → Deferred (Waiver)"),
                            ("calibration_cancelled", "Calibration → Cancelled"),
                            ("system_downtime_created", "System Downtime → Created"),
                            ("asset_decommission", "Asset → Decommission"),
                            ("asset_disposal", "Asset → Disposal"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="high",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_auto_triggers",
                        to="products.businessunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_approval_triggers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The workflow template to instantiate when the event fires.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_triggers",
                        to="products.approvalworkflowtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("business_unit", "event_action", "template")},
            },
        ),
    ]
