# Generated by Django 5.1.6 on 2026-04-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_approvalautotrigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="enforcement_result",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Outcome after enforcement: executed, failed, cancelled, not_applicable.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="intended_changes",
            field=models.JSONField(
                blank=True,
                help_text="JSON describing the blocked action to execute when approved.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="is_enforced",
            field=models.BooleanField(
                default=False,
                help_text="True = this request blocks a real action until approved/rejected.",
            ),
        ),
    ]
