# Generated by Django 5.1.6 on 2026-04-11 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_enforcement_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalautotrigger",
            name="event_action",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="approvalworkflowtemplate",
            name="entity_type",
            field=models.CharField(default="custom", max_length=40),
        ),
        migrations.CreateModel(
            name="ApprovalEntityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique machine key, e.g. purchase_order",
                        max_length=40,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label, e.g. Purchase Order", max_length=100
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System-provided — cannot be deleted"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_entity_types",
                        to="products.businessunit",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "unique_together": {("business_unit", "key")},
            },
        ),
        migrations.CreateModel(
            name="ApprovalEventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique machine key, e.g. product_scrapped",
                        max_length=40,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label, e.g. Product → Scrapped",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Group heading, e.g. Products",
                        max_length=50,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System-provided — cannot be deleted"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_event_types",
                        to="products.businessunit",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "label"],
                "unique_together": {("business_unit", "key")},
            },
        ),
    ]
