# Generated by Django 5.1.6 on 2026-04-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_dynamic_entity_event_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="trigger_event",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The event key (e.g. project_completed) that created this request.",
                max_length=40,
            ),
        ),
    ]
