# Generated by Django 5.1.6 on 2026-04-12 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_approval_request_trigger_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="module",
            field=models.CharField(
                choices=[
                    ("dashboard", "Dashboard & Navigation"),
                    ("user_mgmt", "User Management"),
                    ("stream_admin", "Stream & BU Administration"),
                    ("inventory", "Inventory & Products"),
                    ("sys_alloc", "System Allocation"),
                    ("reservations", "Reservations & Booking"),
                    ("calibration", "Calibration & Maintenance"),
                    ("compliance", "Compliance & Regulatory"),
                    ("analytics", "Analytics & Tracking"),
                    ("collaboration", "Collaboration"),
                    ("support", "Support & Help"),
                    ("vendors", "Vendors & Supply Chain"),
                    ("ai", "AI Features"),
                    ("approvals", "Approval Workflows"),
                    ("search", "Global Search"),
                    ("admin", "Administration & Audit"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ShiftHandoverLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "handover_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: SHL-YYYYMMDD-XXXX",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "shift_date",
                    models.DateField(help_text="Date of the shift being handed over"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "systems_running",
                    models.TextField(
                        blank=True,
                        help_text="Systems currently running — what tests, ETA, any special notes",
                    ),
                ),
                (
                    "pending_actions",
                    models.TextField(
                        blank=True,
                        help_text="Tasks started but not completed — what needs follow-up",
                    ),
                ),
                (
                    "blockers_issues",
                    models.TextField(
                        blank=True,
                        help_text="Blocked items, equipment down, parts ordered, escalations",
                    ),
                ),
                (
                    "safety_notes",
                    models.TextField(
                        blank=True,
                        help_text="Safety incidents, spills, hazards, PPE alerts",
                    ),
                ),
                (
                    "bookings_handoff",
                    models.TextField(
                        blank=True,
                        help_text="Upcoming bookings the next shift should be aware of",
                    ),
                ),
                (
                    "general_notes",
                    models.TextField(
                        blank=True,
                        help_text="Visitor schedules, audit info, miscellaneous",
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledgement_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from incoming shift on acknowledgement",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_handovers",
                        to="products.businessunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "outgoing_lead",
                    models.ForeignKey(
                        help_text="Shift lead / person filing the handover",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "outgoing_team",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Other team members on the outgoing shift",
                        related_name="outgoing_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_handovers",
                        to="products.stream",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Handover Log",
                "verbose_name_plural": "Shift Handover Logs",
                "ordering": ["-shift_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftHandoverComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="products.shifthandoverlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Handover Comment",
                "verbose_name_plural": "Handover Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftHandoverAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                            ("comment_added", "Comment Added"),
                            ("reopened", "Reopened"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="products.shifthandoverlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Handover Audit Log",
                "verbose_name_plural": "Handover Audit Logs",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Morning Shift', 'Night Shift'", max_length=60
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code, e.g. 'morning', 'night'", max_length=20
                    ),
                ),
                ("start_time", models.TimeField(help_text="Shift start time")),
                ("end_time", models.TimeField(help_text="Shift end time")),
                (
                    "color",
                    models.CharField(
                        default="#0066cc",
                        help_text="Hex colour for UI badges",
                        max_length=20,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="fas fa-sun",
                        help_text="FontAwesome icon",
                        max_length=60,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_types",
                        to="products.businessunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Type",
                "verbose_name_plural": "Shift Types",
                "ordering": ["sort_order", "start_time"],
                "unique_together": {("code", "business_unit")},
            },
        ),
        migrations.AddField(
            model_name="shifthandoverlog",
            name="shift_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Which shift is ending",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handovers",
                to="products.shifttype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shifthandoverlog",
            unique_together={("stream", "shift_date", "shift_type")},
        ),
    ]
