# Generated by Django 5.1.6 on 2026-04-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_shift_handover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="module",
            field=models.CharField(
                choices=[
                    ("dashboard", "Dashboard & Navigation"),
                    ("user_mgmt", "User Management"),
                    ("stream_admin", "Stream & BU Administration"),
                    ("inventory", "Inventory & Products"),
                    ("sys_alloc", "System Allocation"),
                    ("reservations", "Reservations & Booking"),
                    ("calibration", "Calibration & Maintenance"),
                    ("compliance", "Compliance & Regulatory"),
                    ("analytics", "Analytics & Tracking"),
                    ("collaboration", "Collaboration"),
                    ("support", "Support & Help"),
                    ("vendors", "Vendors & Supply Chain"),
                    ("ai", "AI Features"),
                    ("approvals", "Approval Workflows"),
                    ("operations", "Operations"),
                    ("search", "Global Search"),
                    ("admin", "Administration & Audit"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
